name: PR - Typescript checks

on:
  pull_request:
    branches:
      - dev

jobs:
  pr-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    env:
      IPUSHPULL_API_SECRET: ${{ secrets.IPUSHPULL_API_SECRET }}
      IPUSHPULL_API_KEY: ${{ secrets.IPUSHPULL_API_KEY }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Executing npm install in core
      run: npm install --prefix packages/adaptable && npm run --prefix packages/adaptable rm-native-types
      env:
        CI: true
    - name: tsc-core
      run: npm run --prefix packages/adaptable tsc

    - name: Executing npm install in react
      run: npm install --prefix packages/adaptable-react-aggrid
      env:
        CI: true
    - name: tsc-react
      run: npm run --prefix packages/adaptable-react-aggrid tsc

    - name: Executing npm install in angular
      run: npm install --prefix packages/adaptable-ng-aggrid
      env:
        CI: true
    - name: tsc-angular
      run: npm run --prefix packages/adaptable-ng-aggrid link-core && npm run --prefix packages/adaptable-ng-aggrid tsc

    - name: Executing npm install in plugins:finance
      run: npm install --prefix packages/plugins/finance
      env:
        CI: true

    - name: tsc-plugins-finance
      run: npm run --prefix packages/plugins/finance tsc

    - name: Executing npm install in plugins:nocode-aggrid
      run: npm install --prefix packages/plugins/nocode-aggrid
      env:
        CI: true

    - name: tsc-plugins-nocode-aggrid
      run: npm run --prefix packages/plugins/nocode-aggrid tsc

    - name: Executing npm install in plugins:charts
      run: npm install --prefix packages/plugins/charts
      env:
        CI: true
    - name: tsc-plugins-charts
      run: npm run --prefix packages/plugins/charts tsc

    # - uses: preactjs/compressed-size-action@v1
    #   with:
    #     repo-token: "${{ secrets.AB_DEPLOY_GITHUB_TOKEN }}"
    #     build-script: ci-build-core-check-size
