name: RELEASE
on:
  pull_request:
      branches:
        - master
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    env:
      IPUSHPULL_API_SECRET: ${{ secrets.IPUSHPULL_API_SECRET }}
      IPUSHPULL_API_KEY: ${{ secrets.IPUSHPULL_API_KEY }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: "./.github/actions/will-release-check"
      env:
        PRIVATE_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

    # - name: check if release needed
    #   run: |
    #     [ -z "${WILL_RELEASE_CMD}" ] && { echo 'Not proceeding, since no release commit message found'; exit 78; };

    - name: Echo whoami
      run: npm whoami --registry=https://registry.adaptabletools.com

    - name: Echo publish cmd
      run: echo $WILL_RELEASE_CMD

    - name: Set git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "SHIP IT"

    - name: Bump version
      run: npm run bump:${WILL_RELEASE_TYPE}

    - name: Executing npm install in root
      run: npm i

    - name: Executing npm install in core
      run: npm run install-core
      env:
        CI: true

    - name: Building core
      run: cd packages/adaptableblotter && npm run build-prod-no-cleanup


    - name: Executing npm install in react
      run: npm run install-react
      env:
        CI: true

    - name: Building react
      run: cd packages/adaptableblotter-react-aggrid && npm run build-prod-no-cleanup


    - name: Executing npm install in angular
      run: npm run install-angular
      env:
        CI: true

    - name: Building angular
      run: cd packages/adaptableblotter-ng-aggrid && npm run build-prod-no-cleanup

    - name: Executing npm install in nocode
      run: npm run install-nocode
      env:
        CI: true

    - name: Building nocode
      run: cd packages/adaptableblotter-nocode && npm run build-prod-no-cleanup

    - name: Ship it
      uses: "./.github/actions/execute-cmd"
      with:
        cmd_to_execute: $WILL_RELEASE_CMD

    - run: git diff
    - run: cat package.json

    - name: Push changes
      uses: "./.github/actions/git-push-action"
      with:
          branch: master
          github_token: ${{ secrets.AB_DEPLOY_GITHUB_TOKEN }}

    - name: Send version to slack
      uses: "./.github/actions/send-version-to-slack"
      with:
          slack_webhook_notify: ${{ secrets.SLACK_WEBHOOK_NOTIFY }}






    #node scripts/registry-publish.js

#     - name: Executing npm install in react
#       run: npm install --prefix packages/adaptableblotter-react-aggrid
#       env:
#         CI: true
#     - name: tsc-react
#       run: npm run --prefix packages/adaptableblotter-react-aggrid tsc
#     - name: Executing npm install in angular
#       run: npm install --prefix packages/adaptableblotter-ng-aggrid
#       env:
#         CI: true
#     - name: tsc-angular
#       run: npm run --prefix packages/adaptableblotter-ng-aggrid link-core && npm run --prefix packages/adaptableblotter-ng-aggrid tsc

