name: RELEASE

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: adaptabletools/release-action@v1.17
      with:
        PRIVATE_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

    - name: Echo whoami
      run: npm whoami --registry=https://registry.adaptabletools.com
    - name: Echo publish cmd
      run: echo $PUBLISH_PACKAGE_CMD

    - name: Executing npm install in root
      run: npm i



    - name: git status
      run: git status

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Executing npm install in core
      run: npm run install-core
      env:
        CI: true

    - name: Building core
      run: cd packages/adaptableblotter && npm run build-prod-no-cleanup

    - name: Executing npm install in react
      run: npm run install-react
      env:
        CI: true

    - name: Building react
      run: cd packages/adaptableblotter-react-aggrid && npm run build-prod-no-cleanup

    - name: Executing npm install in angular
      run: npm run install-angular
      env:
        CI: true

    - name: Building angular
      run: cd packages/adaptableblotter-ng-aggrid && npm run build-prod-no-cleanup

    - name: Set git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Actually publish to private registry
      run: npm run canaryrelease

    - name: Push changes
      uses: ad-m/github-push-action@master

    #node scripts/registry-publish.js

#     - name: Executing npm install in react
#       run: npm install --prefix packages/adaptableblotter-react-aggrid
#       env:
#         CI: true
#     - name: tsc-react
#       run: npm run --prefix packages/adaptableblotter-react-aggrid tsc
#     - name: Executing npm install in angular
#       run: npm install --prefix packages/adaptableblotter-ng-aggrid
#       env:
#         CI: true
#     - name: tsc-angular
#       run: npm run --prefix packages/adaptableblotter-ng-aggrid link-core && npm run --prefix packages/adaptableblotter-ng-aggrid tsc

